project:
  name: "RepoSeed"
  oneLiner: "Create your next open source repository with batteries included"
  state: "beta"
  image: "https://github.com/okkur/reposeed/blob/master/media/logo.svg"
  website: ""
  description: |
    Start with the base layer necessary to focus on your project and not on the repository.
    Licensing, structure, documentation and more boilerplate to get you started from your first commit.

vision:
  type: "personal" # personal is the default.
  overview: |
    Providing a generic base layer for new open source repositories.
  items:
    - "Generic seed files as base layer"
    - "Additions to reposeed only for generic usage"
    - "Default useage on first initialization"
    - "Specific additions should be added to the files after generation"
  concept: "Reposeed's core concept is to provide a basic selection of useful templates. With the help of a configuration file and a small substitution engine the project generates a seed layer for new open source repositories."
  aim: "Our aim is to provide a sufficient base to built a new open source project on top of. Reducing the burden for maintainers and decreasing the hurdles to get started."

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/reposeed/labels/starter%20issue"

supportLinks:
  documentation: "/docs"

readme:
  usageExample: |
    ```
    git clone https://github.com/okkur/reposeed.git  
    mkdir YOUR-PROJECT
    cp seed-config.example.yaml YOUR-PROJECT/.seed-config.yaml
    ```  
    Fill in your project's data and remove unnecessary configuration
    ```
    go run cmd/generator.go --input=reposeed/templates --output=YOUR-PROJECT
    ```
    Refine your new base repository to your specific needs

emails:
  commercialSupport: "support@okkurlabs.com"
  security: "security@okkurlabs.com"
  coc: "coc@okkurlabs.com"

copyright:
  owner: "The RepoSeed authors"
  year: "2017"

cla:
  copyrightHolder: "Michael Grosser"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"

repo:
  link: "https://github.com/okkur/reposeed"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-beta-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/okkur/reposeed.svg"
    link: "https://github.com/okkur/reposeed/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/okkur/reposeed.svg"
    link: "LICENSE"
    alt: "license"
