project:
  name: "RepoSeed"
  description: "Repository template for your next open source project"

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/reposeed/labels/starter%20issue"

supportPlatforms:
  - service: "User Mailinglist"
    link: "example.com"

supportLinks:
  documentation: "/docs"

emails:
  commercialSupport: "support@seetheprogress.net"
  security: "security@seetheprogress.net"
  coc: "coc@seetheprogress.net"

copyright:
  owner: "The RepoSeed authors"
  year: "2017"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"
