# general
project:
  name: "Project123"
  description: "Simplest project description you could imagine"

supportPlatforms:
  - service: "Chat"
    link: "chat.example.com"
  - service: "User Mailinglist"
    link: "list.example.com"
  - service: "StackOverflow"
    link: "stackoverflow.example.com"

supportLinks:
  documentation: "/docs"
  examples: "/examples"
  troubleshooting: "/docs/troubleshooting.md

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/reposeed/labels/starter%20issue"

emails:
  commercialSupport: "payed-support@example.com"
  security: "security@example.com"
  coc: "coc@example.com"

copyright:
  owner: "The Project123 authors"
  year: "2017"

maintainers:
  - name: "Big Robot"
    nick: "nickname"
  - name: "Little Marmot"
    nick: "nickname"

repo:
  link: "https://github.com/okkur/reposeed"
  type: "Github"
