project:
  name: "Project123" # required
  description: "Simplest project description you could imagine" # required

vision:
  type: "personal" # personal is the default.
  items:
    - "Only specific categories allowed"
    - "Bugfixes only"
    - "For personal projects only"
  concept: "Project123's core concept to showcase how, why it does what it does."
  aim: "Project123 should only provide a small core and further additions should be done in helper projects/plugins or some sort."


supportPlatforms:
  - service: "Chat"
    link: "chat.example.com"
  - service: "User Mailinglist"
    link: "list.example.com"
  - service: "StackOverflow"
    link: "stackoverflow.example.com"

supportLinks:
  documentation: "/docs"
  examples: "/examples"
  troubleshooting: "/docs/troubleshooting.md

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/reposeed/labels/starter%20issue"

emails:
  commercialSupport: "payed-support@example.com"
  security: "security@example.com" # required
  coc: "coc@example.com" # required

copyright:
  owner: "The Project123 authors" # falls back to project.name
  year: "2017" # required

cla:
  copyrightHolder: "Michael Grosser" # required

maintainers:
  - name: "Big Robot"
    nick: "nickname"
  - name: "Little Marmot"
    nick: "nickname"

repo:
  link: "https://github.com/okkur/reposeed" # required
  type: "Github" # required

issueTemplate:
  questions:
  - "OS"
  - "CLI version"
